# Generated by Django 6.0 on 2026-01-08 13:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='aluno',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='alunos.aluno'),
            preserve_default=False,
        ),
    ]
